import "./globals.css"

// doesn't work for some reason
// import { Inter } from "next/font/google"
// const inter = Inter({ subsets: ['latin'] })
// <body className="inter.className">

// components
import Navbar from "./components/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <>
    <Navbar />
    <main>
      {children}
    </main>
  </>
  )
}
